# Generated by Django 6.0.5 on 2026-06-01 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone_number', models.CharField(max_length=9)),
                ('vehicle_regis_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('current_milleage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='repairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('costs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiclemanagement.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='oil_change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_milleage', models.IntegerField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiclemanagement.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='appointements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiclemanagement.vehicle')),
            ],
        ),
    ]
