# Generated by Django 6.0.5 on 2026-06-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanagement', '0004_appointements_time_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointements',
            old_name='time_slot',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='repairs',
            old_name='date_repaired',
            new_name='date_changed',
        ),
    ]
